export { default as Navbar } from "./Navbar/Navbar";
export { default as Products } from "./Products/Products";
export { default as Cart } from "../components/Cart/Cart";
export {default as Checkout } from "./CheckoutForm/Checkout/Checkout";
export {default as Headwears } from "../components/Categories/Headwears";
export {default as TopClothes } from "../components/Categories/TopClothes";
export {default as BottomClothes } from "../components/Categories/BottomClothes";
export {default as Shoes } from "../components/Categories/Shoes";
export {default as Belts } from "../components/Categories/Belts";
export { default as Footer } from "./Navbar/Footer";